require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AddStatusToMembershipsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # AddStatusToMembership. As you add validations to AddStatusToMembership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AddStatusToMembershipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all add_status_to_memberships as @add_status_to_memberships" do
      add_status_to_membership = AddStatusToMembership.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:add_status_to_memberships)).to eq([add_status_to_membership])
    end
  end

  describe "GET #show" do
    it "assigns the requested add_status_to_membership as @add_status_to_membership" do
      add_status_to_membership = AddStatusToMembership.create! valid_attributes
      get :show, {:id => add_status_to_membership.to_param}, valid_session
      expect(assigns(:add_status_to_membership)).to eq(add_status_to_membership)
    end
  end

  describe "GET #new" do
    it "assigns a new add_status_to_membership as @add_status_to_membership" do
      get :new, {}, valid_session
      expect(assigns(:add_status_to_membership)).to be_a_new(AddStatusToMembership)
    end
  end

  describe "GET #edit" do
    it "assigns the requested add_status_to_membership as @add_status_to_membership" do
      add_status_to_membership = AddStatusToMembership.create! valid_attributes
      get :edit, {:id => add_status_to_membership.to_param}, valid_session
      expect(assigns(:add_status_to_membership)).to eq(add_status_to_membership)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AddStatusToMembership" do
        expect {
          post :create, {:add_status_to_membership => valid_attributes}, valid_session
        }.to change(AddStatusToMembership, :count).by(1)
      end

      it "assigns a newly created add_status_to_membership as @add_status_to_membership" do
        post :create, {:add_status_to_membership => valid_attributes}, valid_session
        expect(assigns(:add_status_to_membership)).to be_a(AddStatusToMembership)
        expect(assigns(:add_status_to_membership)).to be_persisted
      end

      it "redirects to the created add_status_to_membership" do
        post :create, {:add_status_to_membership => valid_attributes}, valid_session
        expect(response).to redirect_to(AddStatusToMembership.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved add_status_to_membership as @add_status_to_membership" do
        post :create, {:add_status_to_membership => invalid_attributes}, valid_session
        expect(assigns(:add_status_to_membership)).to be_a_new(AddStatusToMembership)
      end

      it "re-renders the 'new' template" do
        post :create, {:add_status_to_membership => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested add_status_to_membership" do
        add_status_to_membership = AddStatusToMembership.create! valid_attributes
        put :update, {:id => add_status_to_membership.to_param, :add_status_to_membership => new_attributes}, valid_session
        add_status_to_membership.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested add_status_to_membership as @add_status_to_membership" do
        add_status_to_membership = AddStatusToMembership.create! valid_attributes
        put :update, {:id => add_status_to_membership.to_param, :add_status_to_membership => valid_attributes}, valid_session
        expect(assigns(:add_status_to_membership)).to eq(add_status_to_membership)
      end

      it "redirects to the add_status_to_membership" do
        add_status_to_membership = AddStatusToMembership.create! valid_attributes
        put :update, {:id => add_status_to_membership.to_param, :add_status_to_membership => valid_attributes}, valid_session
        expect(response).to redirect_to(add_status_to_membership)
      end
    end

    context "with invalid params" do
      it "assigns the add_status_to_membership as @add_status_to_membership" do
        add_status_to_membership = AddStatusToMembership.create! valid_attributes
        put :update, {:id => add_status_to_membership.to_param, :add_status_to_membership => invalid_attributes}, valid_session
        expect(assigns(:add_status_to_membership)).to eq(add_status_to_membership)
      end

      it "re-renders the 'edit' template" do
        add_status_to_membership = AddStatusToMembership.create! valid_attributes
        put :update, {:id => add_status_to_membership.to_param, :add_status_to_membership => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested add_status_to_membership" do
      add_status_to_membership = AddStatusToMembership.create! valid_attributes
      expect {
        delete :destroy, {:id => add_status_to_membership.to_param}, valid_session
      }.to change(AddStatusToMembership, :count).by(-1)
    end

    it "redirects to the add_status_to_memberships list" do
      add_status_to_membership = AddStatusToMembership.create! valid_attributes
      delete :destroy, {:id => add_status_to_membership.to_param}, valid_session
      expect(response).to redirect_to(add_status_to_memberships_url)
    end
  end

end
